### ISSUE TITLE
TypeError: load() missing 1 required positional argument: 'export_dir'

### ISSUE THREAD

**Issue by zhaoyongke** [msubzero2000/Griffin-public#1]
Hello, I'm deploying this project on a Jetson AGX Xavier with trials & errors.
Now I ran into this error:

`Griffin-public/Python Apps# python3 main.py
2021-03-01 14:45:06.308416: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.2
Connected to ('localhost', 2300)
Loading TFRT OpenPose model
WARNING:tensorflow:From /home/didi/Griffin-public/Python Apps/pose_estimation/human_detection.py:12: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    pose_estimator = OpenPose('models')
  File "/home/didi/Griffin-public/Python Apps/pose_estimation/openpose.py", line 162, in __init__
    self._human_detector = HumanDetection()
  File "/home/didi/Griffin-public/Python Apps/pose_estimation/human_detection.py", line 12, in __init__
    "models/ssd", tags=None, options=None
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
TypeError: load() missing 1 required positional argument: 'export_dir'`

**Comment by zhaoyongke** [comment]
Solved by update TF.
